<?php

/**
 * @file
 * Provides a li entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function li_theme(): array {
  return [
    'li' => [
      'render element' => 'elements',
    ],
    'guestbook' => [
      'variables' => [
        'form' => NULL,
        'li_list' => NULL,
      ],
    ],
    'li_list' => [
      'template' => 'li-list',
      'variables' => [
        'lis' => NULL,
        'pager' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for li templates.
 *
 * Default template: li.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the li information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_li(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  $variables['#attached']['library'][] = 'li/li-css';
}
