<?php

use Drupal\Core\Render\Element;
use Drupal\Core\Url;


/**
 * @file
 * Implements hook_theme().
 */
function alex_theme($existing, $type, $theme, $path): array {
  return [
    'guest-page' => [
      'variables' => [
        'form' => NULL,
        'reviews' => NULL,
        'pager' => NULL,
      ],
    ],
    'alex' => [
      'template' => 'alex',
      'render element' => 'elements',
    ]
  ];
}

function template_preprocess_alex(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];

  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  $entity = $variables['elements']['#alex'];

  // Add control button.
  $variables['button'] = [
    '#type' => 'link',
    '#title' => 'Manage',
    '#url' => Url::fromRoute('entity.alex.edit', ['alex' => $entity->id()]),
  ];

  // Add default image.
  if (count($variables['content']['avatar']) <= 3) {
    $variables['content']['avatar'] = [
      '#theme' => 'image',
      '#uri' => '/modules/custom/alex/files/user-icon.jpg',
      '#attributes' => [
        'alt' => 'picture',
        'width' => 100,
        'height' => 100,
      ],
    ];
  }

  $variables['#attached']['library'][] = 'alex/alex.reviews';

}
